language: php
dist: trusty
php:
    - '5.6'
    - '7.0'
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: nightly

services:
    - mysql

before_script:
    - mysql -e 'create database suluvir;'
    - composer install
    - composer create-db

install:
    - composer require satooshi/php-coveralls:~1.0

script:
    - phpunit --configuration phpunit.xml

after_success:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
